version: "3.9"

services:
  frontend:
    build: .
    container_name: booking-room-fe-app-1
    ports:
      - "8889:8889"
    networks:
      - booking-room-be_default # gunakan network yang sudah ada

networks:
  booking-room-be_default:
    external: true # penting: network ini sudah ada
